import Register from "@/components/HomeComp/Register";
import styles from "@/styles/Home.module.css";
import Head from "next/head";

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Routine App - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Register />
      </main>
    </div>
  );
}
