import RoutineOutput from "@/components/RoutineOutput/RoutineOutput";
import styles from "@/styles/Home.module.css";
import Head from "next/head";

export default function RoutinePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Routine App - Generated Routine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <RoutineOutput />
      </main>
    </div>
  );
}
